CREATE TABLE `auth_creds` (
	`id` text PRIMARY KEY NOT NULL,
	`client_id` text NOT NULL,
	`noise_key_public` blob NOT NULL,
	`noise_key_private` blob NOT NULL,
	`pairing_ephemeral_key_pair_public` blob NOT NULL,
	`pairing_ephemeral_key_pair_private` blob NOT NULL,
	`signed_identity_key_public` blob NOT NULL,
	`signed_identity_key_private` blob NOT NULL,
	`signed_pre_key_public` blob NOT NULL,
	`signed_pre_key_private` blob NOT NULL,
	`signed_pre_key_signature` blob NOT NULL,
	`signed_pre_key_id` integer NOT NULL,
	`signed_pre_key_timestamp_s` integer,
	`registration_id` integer NOT NULL,
	`adv_secret_key` text NOT NULL,
	`processed_history_messages` text NOT NULL,
	`next_pre_key_id` integer NOT NULL,
	`first_unuploaded_pre_key_id` integer NOT NULL,
	`account_sync_counter` integer NOT NULL,
	`account_settings` text NOT NULL,
	`registered` integer NOT NULL,
	`pairing_code` text,
	`last_prop_hash` text,
	`routing_info` text
);
