CREATE TABLE `chats` (
	`client_id` text NOT NULL,
	`id` text PRIMARY KEY NOT NULL,
	`messages` text,
	`new_jid` text,
	`old_jid` text,
	`last_msg_timestamp` integer,
	`unread_count` integer,
	`read_only` integer,
	`end_of_history_transfer` integer,
	`ephemeral_expiration` integer,
	`ephemeral_setting_timestamp` integer,
	`end_of_history_transfer_type` integer,
	`conversation_timestamp` integer,
	`name` text,
	`p_hash` text,
	`not_spam` integer,
	`archived` integer,
	`disappearing_mode` text,
	`unread_mention_count` integer,
	`marked_as_unread` integer,
	`participant` text,
	`tc_token` text,
	`tc_token_timestamp` integer,
	`contact_primary_identity_key` text,
	`pinned` integer,
	`mute_end_time` integer,
	`security_settings` text,
	`conversation_auth` text,
	`non_admin_marked_as_unread` integer,
	`biz_privacy_status` integer,
	`share_own_pn` integer,
	`pnh_duplicate_lid_thread` integer,
	`lid_jid` text,
	`last_message_recv_timestamp` integer
);
--> statement-breakpoint
CREATE UNIQUE INDEX `chats_client_id_unique` ON `chats` (`client_id`);--> statement-breakpoint
CREATE TABLE `messages` (
	`client_id` text NOT NULL,
	`remote_jid` text,
	`from_me` integer,
	`id` text PRIMARY KEY NOT NULL,
	`participant` text,
	`message` text,
	`message_timestamp` integer,
	`status` integer,
	`push_name` text,
	`broadcast` integer,
	`starred` integer,
	`message_stub_type` integer,
	`message_stub_parameters` text,
	`labels` text,
	`user_receipt` text,
	`reactions` text,
	`media_data` text,
	`poll_updates` text,
	`keep_in_chat` integer,
	`message_secret` text,
	`pin_in_chat` text,
	`chat_id` text,
	FOREIGN KEY (`chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `messages_client_id_unique` ON `messages` (`client_id`);